version: 1.0.{build}
configuration: Release
platform: x64

# Install scripts. (runs after repo cloning)
install:
  - choco install firefox
  # Get the latest stable version of Node.js
  - ps: Install-Product node ''
  - node --version
  - npm --version
  # install modules
  - npm install
  - ps: mkdir bin
  - cmd: dir

before_test:

test_script:
  - npm run build:debug
  - npm run build:prod
  - npm run test
  - npm run doc:build

# Don't actually build.
build: off
