window.esdocSearchIndex = [
  [
    "foglet-core/src/network/communication/abstract/abstract-broadcast.js~abstractbroadcast",
    "class/src/network/communication/abstract/abstract-broadcast.js~AbstractBroadcast.html",
    "<span>AbstractBroadcast</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/abstract/abstract-broadcast.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html",
    "<span>AbstractMethodBuilder</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/builders/abstract-method-builder.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/abstract/abstract-network.js~abstractnetwork",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html",
    "<span>AbstractNetwork</span> <span class=\"search-result-import-path\">foglet-core/src/network/abstract/abstract-network.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/abstract/abstract-overlay.js~abstractoverlay",
    "class/src/network/abstract/abstract-overlay.js~AbstractOverlay.html",
    "<span>AbstractOverlay</span> <span class=\"search-result-import-path\">foglet-core/src/network/abstract/abstract-overlay.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/abstract/abstract-unicast.js~abstractunicast",
    "class/src/network/communication/abstract/abstract-unicast.js~AbstractUnicast.html",
    "<span>AbstractUnicast</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/abstract/abstract-unicast.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/answer-queue.js~answerqueue",
    "class/src/fprotocol/answer-queue.js~AnswerQueue.html",
    "<span>AnswerQueue</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/answer-queue.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/broadcast/broadcast.js~broadcast",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html",
    "<span>Broadcast</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/broadcast/broadcast.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/builders/broadcast-builder.js~broadcastbuilder",
    "class/src/fprotocol/builders/broadcast-builder.js~BroadcastBuilder.html",
    "<span>BroadcastBuilder</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/builders/broadcast-builder.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/communication.js~communication",
    "class/src/network/communication/communication.js~Communication.html",
    "<span>Communication</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/communication.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/abstract/communication-protocol.js~communicationprotocol",
    "class/src/network/communication/abstract/communication-protocol.js~CommunicationProtocol.html",
    "<span>CommunicationProtocol</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/abstract/communication-protocol.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/rps/cyclon/cyclon.js~cyclon",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html",
    "<span>Cyclon</span> <span class=\"search-result-import-path\">foglet-core/src/network/rps/cyclon/cyclon.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/rps/cyclon-adapter.js~cyclonadapter",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html",
    "<span>CyclonAdapter</span> <span class=\"search-result-import-path\">foglet-core/src/network/rps/cyclon-adapter.js</span>",
    "class"
  ],
  [
    "foglet-core/src/foglet.js~foglet",
    "class/src/foglet.js~Foglet.html",
    "<span>Foglet</span> <span class=\"search-result-import-path\">foglet-core/src/foglet.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/foglet-protocol.js~fogletprotocol",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html",
    "<span>FogletProtocol</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/foglet-protocol.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/builders/init-builder.js~initbuilder",
    "class/src/fprotocol/builders/init-builder.js~InitBuilder.html",
    "<span>InitBuilder</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/builders/init-builder.js</span>",
    "class"
  ],
  [
    "foglet-core/src/utils/media.js~media",
    "class/src/utils/media.js~Media.html",
    "<span>Media</span> <span class=\"search-result-import-path\">foglet-core/src/utils/media.js</span>",
    "class"
  ],
  [
    "foglet-core/src/utils/middleware-registry.js~middlewareregistry",
    "class/src/utils/middleware-registry.js~MiddlewareRegistry.html",
    "<span>MiddlewareRegistry</span> <span class=\"search-result-import-path\">foglet-core/src/utils/middleware-registry.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/network.js~network",
    "class/src/network/network.js~Network.html",
    "<span>Network</span> <span class=\"search-result-import-path\">foglet-core/src/network/network.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/network-manager.js~networkmanager",
    "class/src/network/network-manager.js~NetworkManager.html",
    "<span>NetworkManager</span> <span class=\"search-result-import-path\">foglet-core/src/network/network-manager.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/rps/cyclon/partialview.js~partialview",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html",
    "<span>PartialView</span> <span class=\"search-result-import-path\">foglet-core/src/network/rps/cyclon/partialview.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/builders/service-builder.js~servicebuilder",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html",
    "<span>ServiceBuilder</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/builders/service-builder.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/signaling/signaling.js~signaling",
    "class/src/network/signaling/signaling.js~Signaling.html",
    "<span>Signaling</span> <span class=\"search-result-import-path\">foglet-core/src/network/signaling/signaling.js</span>",
    "class"
  ],
  [
    "foglet-core/src/utils/simple-peer-moc.js~simplepeerabstract",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html",
    "<span>SimplePeerAbstract</span> <span class=\"search-result-import-path\">foglet-core/src/utils/simple-peer-moc.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/rps/sprayadapter.js~sprayadapter",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html",
    "<span>SprayAdapter</span> <span class=\"search-result-import-path\">foglet-core/src/network/rps/sprayAdapter.js</span>",
    "class"
  ],
  [
    "foglet-core/src/utils/ssh.js~sshcontrol",
    "class/src/utils/ssh.js~SshControl.html",
    "<span>SshControl</span> <span class=\"search-result-import-path\">foglet-core/src/utils/ssh.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/stream/stream-message.js~streammessage",
    "class/src/network/communication/stream/stream-message.js~StreamMessage.html",
    "<span>StreamMessage</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/stream/stream-message.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/stream/stream-request.js~streamrequest",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html",
    "<span>StreamRequest</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/stream/stream-request.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/abstract/tman-overlay.js~tmanoverlay",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html",
    "<span>TManOverlay</span> <span class=\"search-result-import-path\">foglet-core/src/network/abstract/tman-overlay.js</span>",
    "class"
  ],
  [
    "foglet-core/src/network/communication/unicast/unicast.js~unicast",
    "class/src/network/communication/unicast/unicast.js~Unicast.html",
    "<span>Unicast</span> <span class=\"search-result-import-path\">foglet-core/src/network/communication/unicast/unicast.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/builders/unicast-builder.js~unicastbuilder",
    "class/src/fprotocol/builders/unicast-builder.js~UnicastBuilder.html",
    "<span>UnicastBuilder</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/builders/unicast-builder.js</span>",
    "class"
  ],
  [
    "foglet-core/src/fprotocol/protocol-builder.js~define",
    "function/index.html#static-function-define",
    "<span>define</span> <span class=\"search-result-import-path\">foglet-core/src/fprotocol/protocol-builder.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/foglet.js",
    "file/src/foglet.js.html",
    "src/foglet.js",
    "file"
  ],
  [
    "src/foglet.js~foglet#_id",
    "class/src/foglet.js~Foglet.html#instance-member-_id",
    "src/foglet.js~Foglet#_id",
    "member"
  ],
  [
    "src/foglet.js~foglet#_networkmanager",
    "class/src/foglet.js~Foglet.html#instance-member-_networkManager",
    "src/foglet.js~Foglet#_networkManager",
    "member"
  ],
  [
    "src/foglet.js~foglet#_options",
    "class/src/foglet.js~Foglet.html#instance-member-_options",
    "src/foglet.js~Foglet#_options",
    "member"
  ],
  [
    "src/foglet.js~foglet#_ssh",
    "class/src/foglet.js~Foglet.html#instance-member-_ssh",
    "src/foglet.js~Foglet#_ssh",
    "member"
  ],
  [
    "src/foglet.js~foglet#connection",
    "class/src/foglet.js~Foglet.html#instance-method-connection",
    "src/foglet.js~Foglet#connection",
    "method"
  ],
  [
    "src/foglet.js~foglet#constructor",
    "class/src/foglet.js~Foglet.html#instance-constructor-constructor",
    "src/foglet.js~Foglet#constructor",
    "method"
  ],
  [
    "src/foglet.js~foglet#createmedia",
    "class/src/foglet.js~Foglet.html#instance-method-createMedia",
    "src/foglet.js~Foglet#createMedia",
    "method"
  ],
  [
    "src/foglet.js~foglet#getarcs",
    "class/src/foglet.js~Foglet.html#instance-method-getArcs",
    "src/foglet.js~Foglet#getArcs",
    "method"
  ],
  [
    "src/foglet.js~foglet#getneighbours",
    "class/src/foglet.js~Foglet.html#instance-method-getNeighbours",
    "src/foglet.js~Foglet#getNeighbours",
    "method"
  ],
  [
    "src/foglet.js~foglet#getrandomneighbourid",
    "class/src/foglet.js~Foglet.html#instance-method-getRandomNeighbourId",
    "src/foglet.js~Foglet#getRandomNeighbourId",
    "method"
  ],
  [
    "src/foglet.js~foglet#getreachableneighbours",
    "class/src/foglet.js~Foglet.html#instance-method-getReachableNeighbours",
    "src/foglet.js~Foglet#getReachableNeighbours",
    "method"
  ],
  [
    "src/foglet.js~foglet#id",
    "class/src/foglet.js~Foglet.html#instance-get-id",
    "src/foglet.js~Foglet#id",
    "member"
  ],
  [
    "src/foglet.js~foglet#inviewid",
    "class/src/foglet.js~Foglet.html#instance-get-inViewID",
    "src/foglet.js~Foglet#inViewID",
    "member"
  ],
  [
    "src/foglet.js~foglet#onbroadcast",
    "class/src/foglet.js~Foglet.html#instance-method-onBroadcast",
    "src/foglet.js~Foglet#onBroadcast",
    "method"
  ],
  [
    "src/foglet.js~foglet#onstreambroadcast",
    "class/src/foglet.js~Foglet.html#instance-method-onStreamBroadcast",
    "src/foglet.js~Foglet#onStreamBroadcast",
    "method"
  ],
  [
    "src/foglet.js~foglet#onstreamunicast",
    "class/src/foglet.js~Foglet.html#instance-method-onStreamUnicast",
    "src/foglet.js~Foglet#onStreamUnicast",
    "method"
  ],
  [
    "src/foglet.js~foglet#onunicast",
    "class/src/foglet.js~Foglet.html#instance-method-onUnicast",
    "src/foglet.js~Foglet#onUnicast",
    "method"
  ],
  [
    "src/foglet.js~foglet#outviewid",
    "class/src/foglet.js~Foglet.html#instance-get-outViewID",
    "src/foglet.js~Foglet#outViewID",
    "member"
  ],
  [
    "src/foglet.js~foglet#overlay",
    "class/src/foglet.js~Foglet.html#instance-method-overlay",
    "src/foglet.js~Foglet#overlay",
    "method"
  ],
  [
    "src/foglet.js~foglet#sendbroadcast",
    "class/src/foglet.js~Foglet.html#instance-method-sendBroadcast",
    "src/foglet.js~Foglet#sendBroadcast",
    "method"
  ],
  [
    "src/foglet.js~foglet#sendmulticast",
    "class/src/foglet.js~Foglet.html#instance-method-sendMulticast",
    "src/foglet.js~Foglet#sendMulticast",
    "method"
  ],
  [
    "src/foglet.js~foglet#sendunicast",
    "class/src/foglet.js~Foglet.html#instance-method-sendUnicast",
    "src/foglet.js~Foglet#sendUnicast",
    "method"
  ],
  [
    "src/foglet.js~foglet#share",
    "class/src/foglet.js~Foglet.html#instance-method-share",
    "src/foglet.js~Foglet#share",
    "method"
  ],
  [
    "src/foglet.js~foglet#streambroadcast",
    "class/src/foglet.js~Foglet.html#instance-method-streamBroadcast",
    "src/foglet.js~Foglet#streamBroadcast",
    "method"
  ],
  [
    "src/foglet.js~foglet#streamunicast",
    "class/src/foglet.js~Foglet.html#instance-method-streamUnicast",
    "src/foglet.js~Foglet#streamUnicast",
    "method"
  ],
  [
    "src/foglet.js~foglet#unshare",
    "class/src/foglet.js~Foglet.html#instance-method-unshare",
    "src/foglet.js~Foglet#unshare",
    "method"
  ],
  [
    "src/foglet.js~foglet#use",
    "class/src/foglet.js~Foglet.html#instance-method-use",
    "src/foglet.js~Foglet#use",
    "method"
  ],
  [
    "src/fprotocol/answer-queue.js",
    "file/src/fprotocol/answer-queue.js.html",
    "src/fprotocol/answer-queue.js",
    "file"
  ],
  [
    "src/fprotocol/answer-queue.js~answerqueue#_waitinganswers",
    "class/src/fprotocol/answer-queue.js~AnswerQueue.html#instance-member-_waitingAnswers",
    "src/fprotocol/answer-queue.js~AnswerQueue#_waitingAnswers",
    "member"
  ],
  [
    "src/fprotocol/answer-queue.js~answerqueue#constructor",
    "class/src/fprotocol/answer-queue.js~AnswerQueue.html#instance-constructor-constructor",
    "src/fprotocol/answer-queue.js~AnswerQueue#constructor",
    "method"
  ],
  [
    "src/fprotocol/answer-queue.js~answerqueue#reject",
    "class/src/fprotocol/answer-queue.js~AnswerQueue.html#instance-method-reject",
    "src/fprotocol/answer-queue.js~AnswerQueue#reject",
    "method"
  ],
  [
    "src/fprotocol/answer-queue.js~answerqueue#resolve",
    "class/src/fprotocol/answer-queue.js~AnswerQueue.html#instance-method-resolve",
    "src/fprotocol/answer-queue.js~AnswerQueue#resolve",
    "method"
  ],
  [
    "src/fprotocol/answer-queue.js~answerqueue#stamp",
    "class/src/fprotocol/answer-queue.js~AnswerQueue.html#instance-method-stamp",
    "src/fprotocol/answer-queue.js~AnswerQueue#stamp",
    "method"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js",
    "file/src/fprotocol/builders/abstract-method-builder.js.html",
    "src/fprotocol/builders/abstract-method-builder.js",
    "file"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#_camelcasedname",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-member-_camelCasedName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#_camelCasedName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#_capitalizedcamelcase",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-member-_capitalizedCamelCase",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#_capitalizedCamelCase",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#_servicename",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-member-_serviceName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#_serviceName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#afterreceivename",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-get-afterReceiveName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#afterReceiveName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#aftersendname",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-get-afterSendName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#afterSendName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#beforereceivename",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-get-beforeReceiveName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#beforeReceiveName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#beforesendname",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-get-beforeSendName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#beforeSendName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#buildafterhooks",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-method-buildAfterHooks",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#buildAfterHooks",
    "method"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#buildbeforehooks",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-method-buildBeforeHooks",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#buildBeforeHooks",
    "method"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#buildhandler",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-method-buildHandler",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#buildHandler",
    "method"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#buildservice",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-method-buildService",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#buildService",
    "method"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#constructor",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-constructor-constructor",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#constructor",
    "method"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#handlername",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-get-handlerName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#handlerName",
    "member"
  ],
  [
    "src/fprotocol/builders/abstract-method-builder.js~abstractmethodbuilder#methodname",
    "class/src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder.html#instance-get-methodName",
    "src/fprotocol/builders/abstract-method-builder.js~AbstractMethodBuilder#methodName",
    "member"
  ],
  [
    "src/fprotocol/builders/broadcast-builder.js",
    "file/src/fprotocol/builders/broadcast-builder.js.html",
    "src/fprotocol/builders/broadcast-builder.js",
    "file"
  ],
  [
    "src/fprotocol/builders/broadcast-builder.js~broadcastbuilder#buildservice",
    "class/src/fprotocol/builders/broadcast-builder.js~BroadcastBuilder.html#instance-method-buildService",
    "src/fprotocol/builders/broadcast-builder.js~BroadcastBuilder#buildService",
    "method"
  ],
  [
    "src/fprotocol/builders/init-builder.js",
    "file/src/fprotocol/builders/init-builder.js.html",
    "src/fprotocol/builders/init-builder.js",
    "file"
  ],
  [
    "src/fprotocol/builders/init-builder.js~initbuilder#_callback",
    "class/src/fprotocol/builders/init-builder.js~InitBuilder.html#instance-member-_callback",
    "src/fprotocol/builders/init-builder.js~InitBuilder#_callback",
    "member"
  ],
  [
    "src/fprotocol/builders/init-builder.js~initbuilder#apply",
    "class/src/fprotocol/builders/init-builder.js~InitBuilder.html#instance-method-apply",
    "src/fprotocol/builders/init-builder.js~InitBuilder#apply",
    "method"
  ],
  [
    "src/fprotocol/builders/init-builder.js~initbuilder#constructor",
    "class/src/fprotocol/builders/init-builder.js~InitBuilder.html#instance-constructor-constructor",
    "src/fprotocol/builders/init-builder.js~InitBuilder#constructor",
    "method"
  ],
  [
    "src/fprotocol/builders/service-builder.js",
    "file/src/fprotocol/builders/service-builder.js.html",
    "src/fprotocol/builders/service-builder.js",
    "file"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#_afterhooks",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-member-_afterHooks",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#_afterHooks",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#_beforehooks",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-member-_beforeHooks",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#_beforeHooks",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#_builder",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-member-_builder",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#_builder",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#_handler",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-member-_handler",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#_handler",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#_servicename",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-member-_serviceName",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#_serviceName",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#_validate",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-method-_validate",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#_validate",
    "method"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#after",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-get-after",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#after",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#apply",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-method-apply",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#apply",
    "method"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#before",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-get-before",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#before",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#constructor",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-constructor-constructor",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#constructor",
    "method"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#is",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-get-is",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#is",
    "member"
  ],
  [
    "src/fprotocol/builders/service-builder.js~servicebuilder#on",
    "class/src/fprotocol/builders/service-builder.js~ServiceBuilder.html#instance-get-on",
    "src/fprotocol/builders/service-builder.js~ServiceBuilder#on",
    "member"
  ],
  [
    "src/fprotocol/builders/unicast-builder.js",
    "file/src/fprotocol/builders/unicast-builder.js.html",
    "src/fprotocol/builders/unicast-builder.js",
    "file"
  ],
  [
    "src/fprotocol/builders/unicast-builder.js~unicastbuilder#buildservice",
    "class/src/fprotocol/builders/unicast-builder.js~UnicastBuilder.html#instance-method-buildService",
    "src/fprotocol/builders/unicast-builder.js~UnicastBuilder#buildService",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js",
    "file/src/fprotocol/foglet-protocol.js.html",
    "src/fprotocol/foglet-protocol.js",
    "file"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_answerqueue",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-member-_answerQueue",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_answerQueue",
    "member"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_answerreject",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_answerReject",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_answerReject",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_answerreply",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_answerReply",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_answerReply",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_foglet",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-member-_foglet",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_foglet",
    "member"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_handlebroadcast",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_handleBroadcast",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_handleBroadcast",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_handleunicast",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_handleUnicast",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_handleUnicast",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_inithandlers",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_initHandlers",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_initHandlers",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_name",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-member-_name",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_name",
    "member"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_sendbroadcast",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_sendBroadcast",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_sendBroadcast",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#_sendunicast",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-method-_sendUnicast",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#_sendUnicast",
    "method"
  ],
  [
    "src/fprotocol/foglet-protocol.js~fogletprotocol#constructor",
    "class/src/fprotocol/foglet-protocol.js~FogletProtocol.html#instance-constructor-constructor",
    "src/fprotocol/foglet-protocol.js~FogletProtocol#constructor",
    "method"
  ],
  [
    "src/fprotocol/protocol-builder.js",
    "file/src/fprotocol/protocol-builder.js.html",
    "src/fprotocol/protocol-builder.js",
    "file"
  ],
  [
    "src/fprotocol/utils.js",
    "file/src/fprotocol/utils.js.html",
    "src/fprotocol/utils.js",
    "file"
  ],
  [
    "src/network/abstract/abstract-network.js",
    "file/src/network/abstract/abstract-network.js.html",
    "src/network/abstract/abstract-network.js",
    "file"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#_buildrps",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-method-_buildRPS",
    "src/network/abstract/abstract-network.js~AbstractNetwork#_buildRPS",
    "method"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#_id",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-member-_id",
    "src/network/abstract/abstract-network.js~AbstractNetwork#_id",
    "member"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#_options",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-member-_options",
    "src/network/abstract/abstract-network.js~AbstractNetwork#_options",
    "member"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#_rps",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-member-_rps",
    "src/network/abstract/abstract-network.js~AbstractNetwork#_rps",
    "member"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#constructor",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-constructor-constructor",
    "src/network/abstract/abstract-network.js~AbstractNetwork#constructor",
    "method"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#getneighbours",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-method-getNeighbours",
    "src/network/abstract/abstract-network.js~AbstractNetwork#getNeighbours",
    "method"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#id",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-get-id",
    "src/network/abstract/abstract-network.js~AbstractNetwork#id",
    "member"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#inviewid",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-get-inviewId",
    "src/network/abstract/abstract-network.js~AbstractNetwork#inviewId",
    "member"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#outviewid",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-get-outviewId",
    "src/network/abstract/abstract-network.js~AbstractNetwork#outviewId",
    "member"
  ],
  [
    "src/network/abstract/abstract-network.js~abstractnetwork#rps",
    "class/src/network/abstract/abstract-network.js~AbstractNetwork.html#instance-get-rps",
    "src/network/abstract/abstract-network.js~AbstractNetwork#rps",
    "member"
  ],
  [
    "src/network/abstract/abstract-overlay.js",
    "file/src/network/abstract/abstract-overlay.js.html",
    "src/network/abstract/abstract-overlay.js",
    "file"
  ],
  [
    "src/network/abstract/abstract-overlay.js~abstractoverlay#constructor",
    "class/src/network/abstract/abstract-overlay.js~AbstractOverlay.html#instance-constructor-constructor",
    "src/network/abstract/abstract-overlay.js~AbstractOverlay#constructor",
    "method"
  ],
  [
    "src/network/abstract/abstract-overlay.js~abstractoverlay#manager",
    "class/src/network/abstract/abstract-overlay.js~AbstractOverlay.html#instance-member-manager",
    "src/network/abstract/abstract-overlay.js~AbstractOverlay#manager",
    "member"
  ],
  [
    "src/network/abstract/tman-overlay.js",
    "file/src/network/abstract/tman-overlay.js.html",
    "src/network/abstract/tman-overlay.js",
    "file"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#_buildrps",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-method-_buildRPS",
    "src/network/abstract/tman-overlay.js~TManOverlay#_buildRPS",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#_descriptortimeout",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-method-_descriptorTimeout",
    "src/network/abstract/tman-overlay.js~TManOverlay#_descriptorTimeout",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#_manager",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-member-_manager",
    "src/network/abstract/tman-overlay.js~TManOverlay#_manager",
    "member"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#_rankpeers",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-method-_rankPeers",
    "src/network/abstract/tman-overlay.js~TManOverlay#_rankPeers",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#_rankingfunction",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-method-_rankingFunction",
    "src/network/abstract/tman-overlay.js~TManOverlay#_rankingFunction",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#_startdescriptor",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-method-_startDescriptor",
    "src/network/abstract/tman-overlay.js~TManOverlay#_startDescriptor",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#constructor",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-constructor-constructor",
    "src/network/abstract/tman-overlay.js~TManOverlay#constructor",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#descriptor",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-get-descriptor",
    "src/network/abstract/tman-overlay.js~TManOverlay#descriptor",
    "member"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#descriptor",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-set-descriptor",
    "src/network/abstract/tman-overlay.js~TManOverlay#descriptor",
    "member"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#getneighbours",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-method-getNeighbours",
    "src/network/abstract/tman-overlay.js~TManOverlay#getNeighbours",
    "method"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#inviewid",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-get-inviewId",
    "src/network/abstract/tman-overlay.js~TManOverlay#inviewId",
    "member"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#options",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-member-options",
    "src/network/abstract/tman-overlay.js~TManOverlay#options",
    "member"
  ],
  [
    "src/network/abstract/tman-overlay.js~tmanoverlay#outviewid",
    "class/src/network/abstract/tman-overlay.js~TManOverlay.html#instance-get-outviewId",
    "src/network/abstract/tman-overlay.js~TManOverlay#outviewId",
    "member"
  ],
  [
    "src/network/communication/abstract/abstract-broadcast.js",
    "file/src/network/communication/abstract/abstract-broadcast.js.html",
    "src/network/communication/abstract/abstract-broadcast.js",
    "file"
  ],
  [
    "src/network/communication/abstract/abstract-broadcast.js~abstractbroadcast#_unicast",
    "class/src/network/communication/abstract/abstract-broadcast.js~AbstractBroadcast.html#instance-member-_unicast",
    "src/network/communication/abstract/abstract-broadcast.js~AbstractBroadcast#_unicast",
    "member"
  ],
  [
    "src/network/communication/abstract/abstract-broadcast.js~abstractbroadcast#constructor",
    "class/src/network/communication/abstract/abstract-broadcast.js~AbstractBroadcast.html#instance-constructor-constructor",
    "src/network/communication/abstract/abstract-broadcast.js~AbstractBroadcast#constructor",
    "method"
  ],
  [
    "src/network/communication/abstract/abstract-unicast.js",
    "file/src/network/communication/abstract/abstract-unicast.js.html",
    "src/network/communication/abstract/abstract-unicast.js",
    "file"
  ],
  [
    "src/network/communication/abstract/abstract-unicast.js~abstractunicast#constructor",
    "class/src/network/communication/abstract/abstract-unicast.js~AbstractUnicast.html#instance-constructor-constructor",
    "src/network/communication/abstract/abstract-unicast.js~AbstractUnicast#constructor",
    "method"
  ],
  [
    "src/network/communication/abstract/communication-protocol.js",
    "file/src/network/communication/abstract/communication-protocol.js.html",
    "src/network/communication/abstract/communication-protocol.js",
    "file"
  ],
  [
    "src/network/communication/abstract/communication-protocol.js~communicationprotocol#_protocol",
    "class/src/network/communication/abstract/communication-protocol.js~CommunicationProtocol.html#instance-member-_protocol",
    "src/network/communication/abstract/communication-protocol.js~CommunicationProtocol#_protocol",
    "member"
  ],
  [
    "src/network/communication/abstract/communication-protocol.js~communicationprotocol#_receive",
    "class/src/network/communication/abstract/communication-protocol.js~CommunicationProtocol.html#instance-method-_receive",
    "src/network/communication/abstract/communication-protocol.js~CommunicationProtocol#_receive",
    "method"
  ],
  [
    "src/network/communication/abstract/communication-protocol.js~communicationprotocol#_source",
    "class/src/network/communication/abstract/communication-protocol.js~CommunicationProtocol.html#instance-member-_source",
    "src/network/communication/abstract/communication-protocol.js~CommunicationProtocol#_source",
    "member"
  ],
  [
    "src/network/communication/abstract/communication-protocol.js~communicationprotocol#constructor",
    "class/src/network/communication/abstract/communication-protocol.js~CommunicationProtocol.html#instance-constructor-constructor",
    "src/network/communication/abstract/communication-protocol.js~CommunicationProtocol#constructor",
    "method"
  ],
  [
    "src/network/communication/abstract/communication-protocol.js~communicationprotocol#send",
    "class/src/network/communication/abstract/communication-protocol.js~CommunicationProtocol.html#instance-method-send",
    "src/network/communication/abstract/communication-protocol.js~CommunicationProtocol#send",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js",
    "file/src/network/communication/broadcast/broadcast.js.html",
    "src/network/communication/broadcast/broadcast.js",
    "file"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_buffer",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-member-_buffer",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_buffer",
    "member"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_bufferantientropy",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-member-_bufferAntiEntropy",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_bufferAntiEntropy",
    "member"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_causality",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-member-_causality",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_causality",
    "member"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_defaultbehaviorantientropy",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-_defaultBehaviorAntiEntropy",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_defaultBehaviorAntiEntropy",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_findinbuffer",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-_findInBuffer",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_findInBuffer",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_intervalantientropy",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-member-_intervalAntiEntropy",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_intervalAntiEntropy",
    "member"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_receive",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-_receive",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_receive",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_reviewbuffer",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-_reviewBuffer",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_reviewBuffer",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_sendall",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-_sendAll",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_sendAll",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#_shouldstoppropagation",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-_shouldStopPropagation",
    "src/network/communication/broadcast/broadcast.js~Broadcast#_shouldStopPropagation",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#clearantientropy",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-clearAntiEntropy",
    "src/network/communication/broadcast/broadcast.js~Broadcast#clearAntiEntropy",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#constructor",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-constructor-constructor",
    "src/network/communication/broadcast/broadcast.js~Broadcast#constructor",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#options",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-member-options",
    "src/network/communication/broadcast/broadcast.js~Broadcast#options",
    "member"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#send",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-send",
    "src/network/communication/broadcast/broadcast.js~Broadcast#send",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#sendantientropyresponse",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-sendAntiEntropyResponse",
    "src/network/communication/broadcast/broadcast.js~Broadcast#sendAntiEntropyResponse",
    "method"
  ],
  [
    "src/network/communication/broadcast/broadcast.js~broadcast#startantientropy",
    "class/src/network/communication/broadcast/broadcast.js~Broadcast.html#instance-method-startAntiEntropy",
    "src/network/communication/broadcast/broadcast.js~Broadcast#startAntiEntropy",
    "method"
  ],
  [
    "src/network/communication/broadcast/messages.js",
    "file/src/network/communication/broadcast/messages.js.html",
    "src/network/communication/broadcast/messages.js",
    "file"
  ],
  [
    "src/network/communication/communication.js",
    "file/src/network/communication/communication.js.html",
    "src/network/communication/communication.js",
    "file"
  ],
  [
    "src/network/communication/communication.js~communication#_activestreams",
    "class/src/network/communication/communication.js~Communication.html#instance-member-_activeStreams",
    "src/network/communication/communication.js~Communication#_activeStreams",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#_broadcaststreams",
    "class/src/network/communication/communication.js~Communication.html#instance-member-_broadcastStreams",
    "src/network/communication/communication.js~Communication#_broadcastStreams",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#_closestream",
    "class/src/network/communication/communication.js~Communication.html#instance-method-_closeStream",
    "src/network/communication/communication.js~Communication#_closeStream",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#_handlestreammessage",
    "class/src/network/communication/communication.js~Communication.html#instance-method-_handleStreamMessage",
    "src/network/communication/communication.js~Communication#_handleStreamMessage",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#_middlewares",
    "class/src/network/communication/communication.js~Communication.html#instance-member-_middlewares",
    "src/network/communication/communication.js~Communication#_middlewares",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#_unicaststreams",
    "class/src/network/communication/communication.js~Communication.html#instance-member-_unicastStreams",
    "src/network/communication/communication.js~Communication#_unicastStreams",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#broadcast",
    "class/src/network/communication/communication.js~Communication.html#instance-member-broadcast",
    "src/network/communication/communication.js~Communication#broadcast",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#constructor",
    "class/src/network/communication/communication.js~Communication.html#instance-constructor-constructor",
    "src/network/communication/communication.js~Communication#constructor",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#network",
    "class/src/network/communication/communication.js~Communication.html#instance-member-network",
    "src/network/communication/communication.js~Communication#network",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#onbroadcast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-onBroadcast",
    "src/network/communication/communication.js~Communication#onBroadcast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#ononcebroadcast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-onOnceBroadcast",
    "src/network/communication/communication.js~Communication#onOnceBroadcast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#ononceunicast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-onOnceUnicast",
    "src/network/communication/communication.js~Communication#onOnceUnicast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#onstreambroadcast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-onStreamBroadcast",
    "src/network/communication/communication.js~Communication#onStreamBroadcast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#onstreamunicast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-onStreamUnicast",
    "src/network/communication/communication.js~Communication#onStreamUnicast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#onunicast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-onUnicast",
    "src/network/communication/communication.js~Communication#onUnicast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#removeallbroacastcallback",
    "class/src/network/communication/communication.js~Communication.html#instance-method-removeAllBroacastCallback",
    "src/network/communication/communication.js~Communication#removeAllBroacastCallback",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#removeallunicastcallback",
    "class/src/network/communication/communication.js~Communication.html#instance-method-removeAllUnicastCallback",
    "src/network/communication/communication.js~Communication#removeAllUnicastCallback",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#sendbroadcast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-sendBroadcast",
    "src/network/communication/communication.js~Communication#sendBroadcast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#sendmulticast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-sendMulticast",
    "src/network/communication/communication.js~Communication#sendMulticast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#sendunicast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-sendUnicast",
    "src/network/communication/communication.js~Communication#sendUnicast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#streambroadcast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-streamBroadcast",
    "src/network/communication/communication.js~Communication#streamBroadcast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#streamunicast",
    "class/src/network/communication/communication.js~Communication.html#instance-method-streamUnicast",
    "src/network/communication/communication.js~Communication#streamUnicast",
    "method"
  ],
  [
    "src/network/communication/communication.js~communication#unicast",
    "class/src/network/communication/communication.js~Communication.html#instance-member-unicast",
    "src/network/communication/communication.js~Communication#unicast",
    "member"
  ],
  [
    "src/network/communication/communication.js~communication#use",
    "class/src/network/communication/communication.js~Communication.html#instance-method-use",
    "src/network/communication/communication.js~Communication#use",
    "method"
  ],
  [
    "src/network/communication/stream/messages.js",
    "file/src/network/communication/stream/messages.js.html",
    "src/network/communication/stream/messages.js",
    "file"
  ],
  [
    "src/network/communication/stream/stream-message.js",
    "file/src/network/communication/stream/stream-message.js.html",
    "src/network/communication/stream/stream-message.js",
    "file"
  ],
  [
    "src/network/communication/stream/stream-message.js~streammessage#_trailers",
    "class/src/network/communication/stream/stream-message.js~StreamMessage.html#instance-member-_trailers",
    "src/network/communication/stream/stream-message.js~StreamMessage#_trailers",
    "member"
  ],
  [
    "src/network/communication/stream/stream-message.js~streammessage#constructor",
    "class/src/network/communication/stream/stream-message.js~StreamMessage.html#instance-constructor-constructor",
    "src/network/communication/stream/stream-message.js~StreamMessage#constructor",
    "method"
  ],
  [
    "src/network/communication/stream/stream-message.js~streammessage#trailers",
    "class/src/network/communication/stream/stream-message.js~StreamMessage.html#instance-get-trailers",
    "src/network/communication/stream/stream-message.js~StreamMessage#trailers",
    "member"
  ],
  [
    "src/network/communication/stream/stream-request.js",
    "file/src/network/communication/stream/stream-request.js.html",
    "src/network/communication/stream/stream-request.js",
    "file"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#_final",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-method-_final",
    "src/network/communication/stream/stream-request.js~StreamRequest#_final",
    "method"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#_id",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-member-_id",
    "src/network/communication/stream/stream-request.js~StreamRequest#_id",
    "member"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#_last_id",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-member-_last_id",
    "src/network/communication/stream/stream-request.js~StreamRequest#_last_id",
    "member"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#_send",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-member-_send",
    "src/network/communication/stream/stream-request.js~StreamRequest#_send",
    "member"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#_trailers",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-member-_trailers",
    "src/network/communication/stream/stream-request.js~StreamRequest#_trailers",
    "member"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#_write",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-method-_write",
    "src/network/communication/stream/stream-request.js~StreamRequest#_write",
    "method"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#addtrailer",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-method-addTrailer",
    "src/network/communication/stream/stream-request.js~StreamRequest#addTrailer",
    "method"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#constructor",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-constructor-constructor",
    "src/network/communication/stream/stream-request.js~StreamRequest#constructor",
    "method"
  ],
  [
    "src/network/communication/stream/stream-request.js~streamrequest#destroy",
    "class/src/network/communication/stream/stream-request.js~StreamRequest.html#instance-method-destroy",
    "src/network/communication/stream/stream-request.js~StreamRequest#destroy",
    "method"
  ],
  [
    "src/network/communication/unicast/unicast.js",
    "file/src/network/communication/unicast/unicast.js.html",
    "src/network/communication/unicast/unicast.js",
    "file"
  ],
  [
    "src/network/communication/unicast/unicast.js~unicast#_receive",
    "class/src/network/communication/unicast/unicast.js~Unicast.html#instance-method-_receive",
    "src/network/communication/unicast/unicast.js~Unicast#_receive",
    "method"
  ],
  [
    "src/network/communication/unicast/unicast.js~unicast#_unicast",
    "class/src/network/communication/unicast/unicast.js~Unicast.html#instance-member-_unicast",
    "src/network/communication/unicast/unicast.js~Unicast#_unicast",
    "member"
  ],
  [
    "src/network/communication/unicast/unicast.js~unicast#constructor",
    "class/src/network/communication/unicast/unicast.js~Unicast.html#instance-constructor-constructor",
    "src/network/communication/unicast/unicast.js~Unicast#constructor",
    "method"
  ],
  [
    "src/network/communication/unicast/unicast.js~unicast#send",
    "class/src/network/communication/unicast/unicast.js~Unicast.html#instance-method-send",
    "src/network/communication/unicast/unicast.js~Unicast#send",
    "method"
  ],
  [
    "src/network/communication/unicast/unicast.js~unicast#sendmultiple",
    "class/src/network/communication/unicast/unicast.js~Unicast.html#instance-method-sendMultiple",
    "src/network/communication/unicast/unicast.js~Unicast#sendMultiple",
    "method"
  ],
  [
    "src/network/network-manager.js",
    "file/src/network/network-manager.js.html",
    "src/network/network-manager.js",
    "file"
  ],
  [
    "src/network/network-manager.js~networkmanager#_buildoverlay",
    "class/src/network/network-manager.js~NetworkManager.html#instance-method-_buildOverlay",
    "src/network/network-manager.js~NetworkManager#_buildOverlay",
    "method"
  ],
  [
    "src/network/network-manager.js~networkmanager#_buildoverlays",
    "class/src/network/network-manager.js~NetworkManager.html#instance-method-_buildOverlays",
    "src/network/network-manager.js~NetworkManager#_buildOverlays",
    "method"
  ],
  [
    "src/network/network-manager.js~networkmanager#_buildrps",
    "class/src/network/network-manager.js~NetworkManager.html#instance-method-_buildRPS",
    "src/network/network-manager.js~NetworkManager#_buildRPS",
    "method"
  ],
  [
    "src/network/network-manager.js~networkmanager#_chooserps",
    "class/src/network/network-manager.js~NetworkManager.html#instance-method-_chooseRps",
    "src/network/network-manager.js~NetworkManager#_chooseRps",
    "method"
  ],
  [
    "src/network/network-manager.js~networkmanager#_options",
    "class/src/network/network-manager.js~NetworkManager.html#instance-member-_options",
    "src/network/network-manager.js~NetworkManager#_options",
    "member"
  ],
  [
    "src/network/network-manager.js~networkmanager#_overlays",
    "class/src/network/network-manager.js~NetworkManager.html#instance-member-_overlays",
    "src/network/network-manager.js~NetworkManager#_overlays",
    "member"
  ],
  [
    "src/network/network-manager.js~networkmanager#_rps",
    "class/src/network/network-manager.js~NetworkManager.html#instance-member-_rps",
    "src/network/network-manager.js~NetworkManager#_rps",
    "member"
  ],
  [
    "src/network/network-manager.js~networkmanager#constructor",
    "class/src/network/network-manager.js~NetworkManager.html#instance-constructor-constructor",
    "src/network/network-manager.js~NetworkManager#constructor",
    "method"
  ],
  [
    "src/network/network-manager.js~networkmanager#overlay",
    "class/src/network/network-manager.js~NetworkManager.html#instance-method-overlay",
    "src/network/network-manager.js~NetworkManager#overlay",
    "method"
  ],
  [
    "src/network/network-manager.js~networkmanager#registermiddleware",
    "class/src/network/network-manager.js~NetworkManager.html#instance-method-registerMiddleware",
    "src/network/network-manager.js~NetworkManager#registerMiddleware",
    "method"
  ],
  [
    "src/network/network-manager.js~overlayconfig",
    "typedef/index.html#static-typedef-OverlayConfig",
    "src/network/network-manager.js~OverlayConfig",
    "typedef"
  ],
  [
    "src/network/network.js",
    "file/src/network/network.js.html",
    "src/network/network.js",
    "file"
  ],
  [
    "src/network/network.js~network#_communication",
    "class/src/network/network.js~Network.html#instance-member-_communication",
    "src/network/network.js~Network#_communication",
    "member"
  ],
  [
    "src/network/network.js~network#_network",
    "class/src/network/network.js~Network.html#instance-member-_network",
    "src/network/network.js~Network#_network",
    "member"
  ],
  [
    "src/network/network.js~network#_protocol",
    "class/src/network/network.js~Network.html#instance-member-_protocol",
    "src/network/network.js~Network#_protocol",
    "member"
  ],
  [
    "src/network/network.js~network#_signaling",
    "class/src/network/network.js~Network.html#instance-member-_signaling",
    "src/network/network.js~Network#_signaling",
    "member"
  ],
  [
    "src/network/network.js~network#communication",
    "class/src/network/network.js~Network.html#instance-get-communication",
    "src/network/network.js~Network#communication",
    "member"
  ],
  [
    "src/network/network.js~network#constructor",
    "class/src/network/network.js~Network.html#instance-constructor-constructor",
    "src/network/network.js~Network#constructor",
    "method"
  ],
  [
    "src/network/network.js~network#network",
    "class/src/network/network.js~Network.html#instance-get-network",
    "src/network/network.js~Network#network",
    "member"
  ],
  [
    "src/network/network.js~network#protocol",
    "class/src/network/network.js~Network.html#instance-get-protocol",
    "src/network/network.js~Network#protocol",
    "member"
  ],
  [
    "src/network/network.js~network#signaling",
    "class/src/network/network.js~Network.html#instance-get-signaling",
    "src/network/network.js~Network#signaling",
    "member"
  ],
  [
    "src/network/network.js~network#use",
    "class/src/network/network.js~Network.html#instance-method-use",
    "src/network/network.js~Network#use",
    "method"
  ],
  [
    "src/network/rps/cyclon-adapter.js",
    "file/src/network/rps/cyclon-adapter.js.html",
    "src/network/rps/cyclon-adapter.js",
    "file"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#_buildrps",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-method-_buildRPS",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#_buildRPS",
    "method"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#constructor",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-constructor-constructor",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#constructor",
    "method"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#getarcs",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-method-getArcs",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#getArcs",
    "method"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#getneighbours",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-method-getNeighbours",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#getNeighbours",
    "method"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#getreachableneighbours",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-method-getReachableNeighbours",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#getReachableNeighbours",
    "method"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#inviewid",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-get-inviewId",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#inviewId",
    "member"
  ],
  [
    "src/network/rps/cyclon-adapter.js~cyclonadapter#outviewid",
    "class/src/network/rps/cyclon-adapter.js~CyclonAdapter.html#instance-get-outviewId",
    "src/network/rps/cyclon-adapter.js~CyclonAdapter#outviewId",
    "member"
  ],
  [
    "src/network/rps/cyclon/cyclon.js",
    "file/src/network/rps/cyclon/cyclon.js.html",
    "src/network/rps/cyclon/cyclon.js",
    "file"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_close",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_close",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_close",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_exchange",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_exchange",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_exchange",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_getsample",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_getSample",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_getSample",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_onarcdown",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_onArcDown",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_onArcDown",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_onbridge",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_onBridge",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_onBridge",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_onexchange",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_onExchange",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_onExchange",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_onjoin",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_onJoin",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_onJoin",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_onleave",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_onLeave",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_onLeave",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_open",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_open",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_open",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_partialview",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-member-_partialView",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_partialView",
    "member"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_periodic",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-member-_periodic",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_periodic",
    "member"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_receive",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_receive",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_receive",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_start",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_start",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_start",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#_stop",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-_stop",
    "src/network/rps/cyclon/cyclon.js~Cyclon#_stop",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#constructor",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-constructor-constructor",
    "src/network/rps/cyclon/cyclon.js~Cyclon#constructor",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#exchange",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-exchange",
    "src/network/rps/cyclon/cyclon.js~Cyclon#exchange",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#getpeers",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-getPeers",
    "src/network/rps/cyclon/cyclon.js~Cyclon#getPeers",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#join",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-method-join",
    "src/network/rps/cyclon/cyclon.js~Cyclon#join",
    "method"
  ],
  [
    "src/network/rps/cyclon/cyclon.js~cyclon#partialview",
    "class/src/network/rps/cyclon/cyclon.js~Cyclon.html#instance-get-partialView",
    "src/network/rps/cyclon/cyclon.js~Cyclon#partialView",
    "member"
  ],
  [
    "src/network/rps/cyclon/partialview.js",
    "file/src/network/rps/cyclon/partialview.js.html",
    "src/network/rps/cyclon/partialview.js",
    "file"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#add",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-method-add",
    "src/network/rps/cyclon/partialview.js~PartialView#add",
    "method"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#increment",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-method-increment",
    "src/network/rps/cyclon/partialview.js~PartialView#increment",
    "method"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#leastfrequent",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-get-leastFrequent",
    "src/network/rps/cyclon/partialview.js~PartialView#leastFrequent",
    "member"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#oldest",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-get-oldest",
    "src/network/rps/cyclon/partialview.js~PartialView#oldest",
    "member"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#removeall",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-method-removeAll",
    "src/network/rps/cyclon/partialview.js~PartialView#removeAll",
    "method"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#removeoldest",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-method-removeOldest",
    "src/network/rps/cyclon/partialview.js~PartialView#removeOldest",
    "method"
  ],
  [
    "src/network/rps/cyclon/partialview.js~partialview#removeyoungest",
    "class/src/network/rps/cyclon/partialview.js~PartialView.html#instance-method-removeYoungest",
    "src/network/rps/cyclon/partialview.js~PartialView#removeYoungest",
    "method"
  ],
  [
    "src/network/rps/sprayadapter.js",
    "file/src/network/rps/sprayAdapter.js.html",
    "src/network/rps/sprayAdapter.js",
    "file"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#_buildrps",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-method-_buildRPS",
    "src/network/rps/sprayAdapter.js~SprayAdapter#_buildRPS",
    "method"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#constructor",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-constructor-constructor",
    "src/network/rps/sprayAdapter.js~SprayAdapter#constructor",
    "method"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#getarcs",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-method-getArcs",
    "src/network/rps/sprayAdapter.js~SprayAdapter#getArcs",
    "method"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#getneighbours",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-method-getNeighbours",
    "src/network/rps/sprayAdapter.js~SprayAdapter#getNeighbours",
    "method"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#getreachableneighbours",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-method-getReachableNeighbours",
    "src/network/rps/sprayAdapter.js~SprayAdapter#getReachableNeighbours",
    "method"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#inviewid",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-get-inviewId",
    "src/network/rps/sprayAdapter.js~SprayAdapter#inviewId",
    "member"
  ],
  [
    "src/network/rps/sprayadapter.js~sprayadapter#outviewid",
    "class/src/network/rps/sprayAdapter.js~SprayAdapter.html#instance-get-outviewId",
    "src/network/rps/sprayAdapter.js~SprayAdapter#outviewId",
    "member"
  ],
  [
    "src/network/signaling/signaling.js",
    "file/src/network/signaling/signaling.js.html",
    "src/network/signaling/signaling.js",
    "file"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_id",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-member-_id",
    "src/network/signaling/signaling.js~Signaling#_id",
    "member"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_manageconnectionerror",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-_manageConnectionError",
    "src/network/signaling/signaling.js~Signaling#_manageConnectionError",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_managedisconnection",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-_manageDisconnection",
    "src/network/signaling/signaling.js~Signaling#_manageDisconnection",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_manageerror",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-_manageError",
    "src/network/signaling/signaling.js~Signaling#_manageError",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_managetimeout",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-_manageTimeout",
    "src/network/signaling/signaling.js~Signaling#_manageTimeout",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_network",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-member-_network",
    "src/network/signaling/signaling.js~Signaling#_network",
    "member"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_signalinginit",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-_signalingInit",
    "src/network/signaling/signaling.js~Signaling#_signalingInit",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_socket",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-member-_socket",
    "src/network/signaling/signaling.js~Signaling#_socket",
    "member"
  ],
  [
    "src/network/signaling/signaling.js~signaling#_source",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-member-_source",
    "src/network/signaling/signaling.js~Signaling#_source",
    "member"
  ],
  [
    "src/network/signaling/signaling.js~signaling#connection",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-connection",
    "src/network/signaling/signaling.js~Signaling#connection",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#constructor",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-constructor-constructor",
    "src/network/signaling/signaling.js~Signaling#constructor",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#direct",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-direct",
    "src/network/signaling/signaling.js~Signaling#direct",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#options",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-member-options",
    "src/network/signaling/signaling.js~Signaling#options",
    "member"
  ],
  [
    "src/network/signaling/signaling.js~signaling#signaling",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-signaling",
    "src/network/signaling/signaling.js~Signaling#signaling",
    "method"
  ],
  [
    "src/network/signaling/signaling.js~signaling#unsignaling",
    "class/src/network/signaling/signaling.js~Signaling.html#instance-method-unsignaling",
    "src/network/signaling/signaling.js~Signaling#unsignaling",
    "method"
  ],
  [
    "src/utils/media.js",
    "file/src/utils/media.js.html",
    "src/utils/media.js",
    "file"
  ],
  [
    "src/utils/media.js~media#ni",
    "class/src/utils/media.js~Media.html#instance-member-NI",
    "src/utils/media.js~Media#NI",
    "member"
  ],
  [
    "src/utils/media.js~media#no",
    "class/src/utils/media.js~Media.html#instance-member-NO",
    "src/utils/media.js~Media#NO",
    "member"
  ],
  [
    "src/utils/media.js~media#_activemedia",
    "class/src/utils/media.js~Media.html#instance-member-_activeMedia",
    "src/utils/media.js~Media#_activeMedia",
    "member"
  ],
  [
    "src/utils/media.js~media#_activestream",
    "class/src/utils/media.js~Media.html#instance-member-_activeStream",
    "src/utils/media.js~Media#_activeStream",
    "member"
  ],
  [
    "src/utils/media.js~media#_communication",
    "class/src/utils/media.js~Media.html#instance-member-_communication",
    "src/utils/media.js~Media#_communication",
    "member"
  ],
  [
    "src/utils/media.js~media#_receive",
    "class/src/utils/media.js~Media.html#instance-method-_receive",
    "src/utils/media.js~Media#_receive",
    "method"
  ],
  [
    "src/utils/media.js~media#_reconstruct",
    "class/src/utils/media.js~Media.html#instance-method-_reconstruct",
    "src/utils/media.js~Media#_reconstruct",
    "method"
  ],
  [
    "src/utils/media.js~media#_setlisteners",
    "class/src/utils/media.js~Media.html#instance-method-_setListeners",
    "src/utils/media.js~Media#_setListeners",
    "method"
  ],
  [
    "src/utils/media.js~media#chunkify",
    "class/src/utils/media.js~Media.html#instance-method-chunkify",
    "src/utils/media.js~Media#chunkify",
    "method"
  ],
  [
    "src/utils/media.js~media#constructor",
    "class/src/utils/media.js~Media.html#instance-constructor-constructor",
    "src/utils/media.js~Media#constructor",
    "method"
  ],
  [
    "src/utils/media.js~media#getstreammedia",
    "class/src/utils/media.js~Media.html#instance-method-getStreamMedia",
    "src/utils/media.js~Media#getStreamMedia",
    "method"
  ],
  [
    "src/utils/media.js~media#i",
    "class/src/utils/media.js~Media.html#instance-member-i",
    "src/utils/media.js~Media#i",
    "member"
  ],
  [
    "src/utils/media.js~media#o",
    "class/src/utils/media.js~Media.html#instance-member-o",
    "src/utils/media.js~Media#o",
    "member"
  ],
  [
    "src/utils/media.js~media#options",
    "class/src/utils/media.js~Media.html#instance-member-options",
    "src/utils/media.js~Media#options",
    "member"
  ],
  [
    "src/utils/media.js~media#pid",
    "class/src/utils/media.js~Media.html#instance-get-pid",
    "src/utils/media.js~Media#pid",
    "member"
  ],
  [
    "src/utils/media.js~media#sendbroadcastoverdatachannel",
    "class/src/utils/media.js~Media.html#instance-method-sendBroadcastOverDataChannel",
    "src/utils/media.js~Media#sendBroadcastOverDataChannel",
    "method"
  ],
  [
    "src/utils/media.js~media#sendunicast",
    "class/src/utils/media.js~Media.html#instance-method-sendUnicast",
    "src/utils/media.js~Media#sendUnicast",
    "method"
  ],
  [
    "src/utils/middleware-registry.js",
    "file/src/utils/middleware-registry.js.html",
    "src/utils/middleware-registry.js",
    "file"
  ],
  [
    "src/utils/middleware-registry.js~middlewareregistry#_middlewares",
    "class/src/utils/middleware-registry.js~MiddlewareRegistry.html#instance-member-_middlewares",
    "src/utils/middleware-registry.js~MiddlewareRegistry#_middlewares",
    "member"
  ],
  [
    "src/utils/middleware-registry.js~middlewareregistry#constructor",
    "class/src/utils/middleware-registry.js~MiddlewareRegistry.html#instance-constructor-constructor",
    "src/utils/middleware-registry.js~MiddlewareRegistry#constructor",
    "method"
  ],
  [
    "src/utils/middleware-registry.js~middlewareregistry#in",
    "class/src/utils/middleware-registry.js~MiddlewareRegistry.html#instance-method-in",
    "src/utils/middleware-registry.js~MiddlewareRegistry#in",
    "method"
  ],
  [
    "src/utils/middleware-registry.js~middlewareregistry#out",
    "class/src/utils/middleware-registry.js~MiddlewareRegistry.html#instance-method-out",
    "src/utils/middleware-registry.js~MiddlewareRegistry#out",
    "method"
  ],
  [
    "src/utils/middleware-registry.js~middlewareregistry#register",
    "class/src/utils/middleware-registry.js~MiddlewareRegistry.html#instance-method-register",
    "src/utils/middleware-registry.js~MiddlewareRegistry#register",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js",
    "file/src/utils/simple-peer-moc.js.html",
    "src/utils/simple-peer-moc.js",
    "file"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#webrtc_support",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-WEBRTC_SUPPORT",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#WEBRTC_SUPPORT",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_close",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_close",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_close",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_connect",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_connect",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_connect",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_connectwith",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_connectWith",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_connectWith",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_createaccept",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_createAccept",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_createAccept",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_createoffer",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_createOffer",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_createOffer",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_error",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_error",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_error",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_init",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_init",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_init",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_isnegotiating",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-_isNegotiating",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_isNegotiating",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_manager",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-_manager",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_manager",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_options",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-_options",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_options",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_reviewmessagebuffer",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_reviewMessageBuffer",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_reviewMessageBuffer",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#_send",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-_send",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#_send",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#connected",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-connected",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#connected",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#connectedwith",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-connectedWith",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#connectedWith",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#constructor",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-constructor-constructor",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#constructor",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#destroy",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-destroy",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#destroy",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#disconnected",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-disconnected",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#disconnected",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#id",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-id",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#id",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#messagebuffer",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-member-messageBuffer",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#messageBuffer",
    "member"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#send",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-send",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#send",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract#signal",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#instance-method-signal",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract#signal",
    "method"
  ],
  [
    "src/utils/simple-peer-moc.js~simplepeerabstract.manager",
    "class/src/utils/simple-peer-moc.js~SimplePeerAbstract.html#static-get-manager",
    "src/utils/simple-peer-moc.js~SimplePeerAbstract.manager",
    "member"
  ],
  [
    "src/utils/ssh.js",
    "file/src/utils/ssh.js.html",
    "src/utils/ssh.js",
    "file"
  ],
  [
    "src/utils/ssh.js~sshcontrol#constructor",
    "class/src/utils/ssh.js~SshControl.html#instance-constructor-constructor",
    "src/utils/ssh.js~SshControl#constructor",
    "method"
  ],
  [
    "src/utils/ssh.js~sshcontrol#deserialize",
    "class/src/utils/ssh.js~SshControl.html#instance-method-deserialize",
    "src/utils/ssh.js~SshControl#deserialize",
    "method"
  ],
  [
    "src/utils/ssh.js~sshcontrol#log",
    "class/src/utils/ssh.js~SshControl.html#instance-method-log",
    "src/utils/ssh.js~SshControl#log",
    "method"
  ],
  [
    "src/utils/ssh.js~sshcontrol#options",
    "class/src/utils/ssh.js~SshControl.html#instance-member-options",
    "src/utils/ssh.js~SshControl#options",
    "member"
  ],
  [
    "src/utils/ssh.js~sshcontrol#signaling",
    "class/src/utils/ssh.js~SshControl.html#instance-member-signaling",
    "src/utils/ssh.js~SshControl#signaling",
    "member"
  ]
]